# Generated by Django 2.2.3 on 2020-02-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDB',
            fields=[
                ('query', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntityDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=64)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrain_fer.QueryDB')),
            ],
        ),
    ]
